spring:
  profiles:
    active:
      #activatedProperties#
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true

  mail:
    host: smtp.allsaintsmusic.com
    username: admin@allsaintsmusic.com
    password:
    default-encoding: UTF-8
    protocol: smtps
    port: 465
    properties:
      mail.smtp:
          auth: true
          starttls:
            enable: true
            required: true